### ISSUE TITLE
Command \linenumbersep undefined

### ISSUE THREAD

**Issue by amontoison** [dpo/latex-styles#11]
Is it possible to not comment by hand this line: https://github.com/dpo/latex-styles/blob/master/styles/siampaper/siampaper.sty#L10
when `\documentclass[review]{siamart190516}` is replaced by `\documentclass[final]{siamart190516}`?

**Comment by dpo** [comment]
Not sure what you mean. If you use `final`, that setting is irrelevant, isn't it?

**Comment by amontoison** [comment]
Yes that setting is irrelevant but I can't compile the PDF because `\renewcommand{\linenumbersep}{40pt}` is failing.
And it's failing because `\linenumbersep` is not define by the siam class when we use `final`.

**Comment by dpo** [comment]
It's possible but will require a little work.

**Comment by amontoison** [comment]
I just tested the following modification and it works
```latex
\ifdefined\linenumbersep
  \renewcommand{\linenumbersep}{40pt}
\fi
```
