### ISSUE TITLE
Can no longer download SIAM zip

### ISSUE THREAD

**Issue by dpo** [dpo/latex-styles#24]
`curl -OL` downloads an html file instead of the zip file.

**Comment by amontoison** [comment]
The repository of `MinAres` have modiifed workflows that only download the cls files.

**Comment by dpo** [comment]
I can no longer download that either.

**Comment by amontoison** [comment]
I tested tonight and I don't have any issue to download the zip archive or the cls file.
Are you still unable to download them?

**Comment by dpo** [comment]
Yes:
```
/tmp ❯ curl -OL https://epubs.siam.org/pb-assets/macros/standard/siamart_220329.zip    13:29:03
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7254    0  7254    0     0  27586      0 --:--:-- --:--:-- --:--:-- 28559
/tmp ❯ file siamart_220329.zip                                                         13:29:12
siamart_220329.zip: HTML document text, ASCII text, with very long lines (2649)
```

**Comment by amontoison** [comment]
I checked again tonight and even if I can download the files, I also have HTML files.
I tried with `wget` and it seems that they block us:
```
alexis@HP-Spectre:~$ wget https://epubs.siam.org/pb-assets/macros/standard/siamart220329.cls
--2023-06-14 02:15:02--  https://epubs.siam.org/pb-assets/macros/standard/siamart220329.cls
Résolution de epubs.siam.org (epubs.siam.org)… 104.18.30.167, 104.18.31.167
Connexion à epubs.siam.org (epubs.siam.org)|104.18.30.167|:443… connecté.
requête HTTP transmise, en attente de la réponse… 403 Forbidden
2023-06-14 02:15:02 erreur 403 : Forbidden.
```

I don't have any issue when I download the files with Firefox.
From what I found online, the request in the browser likely includes authorization headers or cookies, and if we don't have those in our wget/curl call, the site will refuse the download.

**Comment by dpo** [comment]
I wrote to SIAM to ask if they would restore access to the files from the command line.

I found this but it’s outdated: https://github.com/tgkolda/siam-latex. I know it was used at some point to revamp the style files.
